branches:
  - wod
  - wod_ptr
  - interrealm

clone:
  depth: 20
  recursive: true
  submodule_update_remote: true

build:
  prepare_build:
    image: milleniumstudio/drone-clang-mariadb-ace
    commands:
        - mkdir /home/realm
        - mkdir build
  wod_release:
    image: milleniumstudio/drone-clang-mariadb-ace
    commands:
      - cd build
      - cmake .. -DPREFIX=/home/realm -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_WARNINGS=0 -DWITH_COREDEBUG=0 -DTOOLS=0
      - make -j
      - make install
      - make clean
      - mv /home/realm/bin/worldserver /home/realm/bin/worldserver_RelWithDebInfo
      - cd - && ls -la
  wod_asan:
    image: milleniumstudio/drone-clang-mariadb-ace
    commands:
      - cd build
      - cmake .. -DPREFIX=/home/realm -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS="-fsanitize=address -fno-omit-frame-pointer" -DCMAKE_C_FLAGS="-fsanitize=address -fno-omit-frame-pointer" -DWITH_WARNINGS=0 -DWITH_COREDEBUG=0 -DTOOLS=0
      - make -j
      - make install
      - make clean
      - mv /home/realm/bin/worldserver /home/realm/bin/worldserver_Asan
      - cd - && ls -la
    when:
      branch: wod

#publish:
#  docker:
#    username: drone
#    password: $$DOCKER_PASS
#    email: $$DOCKER_EMAIL
#    repo: milleniumstudio/docker-wod
#    tag: latest
#    file: Dockerfile
#    when:
#      branch: wod

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: wow-notification
    username: Drone
    template: >
      Build <https://drone.firestorm-servers.com/MilleniumStudio/Garrosh/{{ build.number }}|{{ repo.name }}#{{ truncate build.commit 7 }}> ({{ build.branch }}) by {{ build.author }} finished with a *{{ build.status }}* status in {{ duration build.started_at build.finished_at }}
