language: cpp
compiler:
  - clang

git:
  depth: 5

branches:
  only:
    - WoD2
    - WoD2_dev
    - WoD2_hotfix
    - 6.1.2

before_install:
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get -qq update
  - sudo apt-get -qq install build-essential gcc g++ make cmake openssl
  - sudo apt-get -qq install libmysqlclient15-dev libmysql++-dev libssl-dev libace-dev libreadline6-dev zlib1g-dev libbz2-dev libtool
  - git clone git@github.com:MilleniumStudio/ms_framework.git dep/ms_framework
  - cd dep/ms_framework
  - git submodule init
  - git submodule update --remote
  - mkdir build
  - cd build
  - cmake ..
  - make -j
  - sudo make install
  - cd ../../../

install:
  # - mysql -uroot -e 'create database test_mysql;'
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_WARNINGS=0 -DWITH_COREDEBUG=0 -DTOOLS=0
  - cd ..

#before_script:
#  - mysql -uroot < sql/create/create_mysql.sql
#  - mysql -utrinity -ptrinity auth < sql/base/auth_database.sql
#  - mysql -utrinity -ptrinity characters < sql/base/characters_database.sql
#  - mysql -utrinity -ptrinity world < sql/base/world_database.sql
#  - mysql -utrinity -ptrinity monitoring < sql/base/monitoring_database.sql
#  - cat sql/updates/world/2015/*/*.sql | mysql -utrinity -ptrinity world
#  - mysql -uroot < sql/create/drop_mysql.sql

script:
  - cd build
  - make -j 12

notifications:
  slack: millenium-studio:hJlKAYRaplFP8GVoH5a7FPqv
