language: cpp
compiler:
  - clang

git:
  depth: 5

branches:
  only:
    - WoD2
    - WoD2_dev
    - WoD2_hotfix
    - 6.1.2

before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install build-essential gcc-4.8 g++-4.8 make cmake openssl
  - sudo apt-get -qq install libmysqlclient15-dev libmysql++-dev libssl-dev libace-dev libreadline6-dev zlib1g-dev libbz2-dev libtool


install:
  - git clone git@github.com:MilleniumStudio/ms_framework.git dep/ms_framework
  - cd dep/ms_framework
  - git submodule init
  - git submodule update --remote
  - mkdir build && cd build
  - cmake ..
  - make -j
  - sudo make install
  - cd ../../../
  - mysql -uroot -e 'create database test_mysql;'

before_script:
  - mysql -uroot < sql/create/create_mysql.sql
  - mysql -umsstudio -pmsstudio auth < sql/base/auth_database.sql
  - mysql -umsstudio -pmsstudio characters < sql/base/characters_database.sql
  - mysql -umsstudio -pmsstudio world < sql/base/world_database.sql
  - mysql -umsstudio -pmsstudio monitoring < sql/base/monitoring_database.sql
  - cat sql/updates/character/2015/$(date +"%m")/*.sql | mysql -msstudio -msstudio characters
  - cat sql/updates/world/2015/$(date +"%m")/*.sql | mysql -umsstudio -pmsstudio world

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_WARNINGS=0 -DWITH_COREDEBUG=0 -DTOOLS=0
  - make -j 12
  - cd ..

#after_success:
#  -

after_script:
  - mysql -uroot < sql/create/drop_mysql.sql

notifications:
  slack: millenium-studio:hJlKAYRaplFP8GVoH5a7FPqv
