language: cpp
compiler:
  - clang

git:
  depth: 10

branches:
  only:
    - wod
    - wod_ptr

before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install build-essential gcc-5 g++-5 make cmake openssl
  - sudo apt-get -qq install libmysqlclient-dev libmysql++-dev libssl-dev libace-dev libreadline6-dev zlib1g-dev libbz2-dev libtool

install:
  - mysql -uroot -e 'create database test_mysql;'

before_script:
  - mysql -uroot < sql/create/create_mysql.sql
  - mysql -umsstudio -pmsstudio auth < sql/base/auth_database.sql
  - mysql -umsstudio -pmsstudio characters < sql/base/characters_database.sql
  - mysql -umsstudio -pmsstudio world < sql/base/world_database.sql
  - mysql -umsstudio -pmsstudio hotfix < sql/base/hotfix_database.sql
  - cat sql/updates/characters/*.sql | mysql -umsstudio -pmsstudio characters
  - cat sql/updates/world/*.sql | mysql -umsstudio -pmsstudio world
  - cat sql/updates/hotfix/*.sql | mysql -umsstudio -pmsstudio hotfix
  - git submodule init && git submodule update --remote

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_WARNINGS=0 -DWITH_COREDEBUG=0 -DTOOLS=0
  - make -j 12
  - cd ..

after_success:
  # -

after_script:
  - mysql -uroot < sql/create/drop_mysql.sql

notifications:
  slack: millenium-studio:hJlKAYRaplFP8GVoH5a7FPqv
